version: '3.8'

services:
  pg-backend:
    container_name: pg-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
